Random testing using config=Config(swarmSwitch=None, verbose=False, reducePool=False, failedLogging=None, exploitBestHint=1, greedyStutter=False, exploit=None, seed=None, generalize=False, useHints=False, localize=False, total=False, speed='FAST', probs='locsample.probs', normalize=False, verboseExploit=False, highLowSwarm=None, replayable=False, essentials=False, noCoverageExploit=False, quickTests=False, relax=False, internal=False, uniqueValuesAnalysis=False, swarm=True, noReassign=False, html=None, fastQuickAnalysis=False, progress=False, swarmLength=None, profile=False, LOCBaseline=0.2, full=True, multiple=True, timedProgress=30, silentFail=False, stopWhenStatements=None, swarmP=0.5, stopWhenBranches=None, noAlphaConvert=False, coverFile='coverage.out', readQuick=False, verboseActions=False, running=False, computeFeatureStats=False, compareFails=False, swarmProbs=None, output='failure.90544.test', genDepth=None, Pcrossover=0.2, quickAnalysis=False, keepLast=False, exploitCeiling=0.1, logging=None, LOCProbs=False, noCheck=False, maxTests=-1, noExceptionMatch=False, Pmutate=0.0, depth=100, showActions=False, throughput=False, noCover=False, timeout=60, stutter=None, uncaught=False, markov=None, startExploit=0)
TEST #31 STEP #68 (0:00:30.009316) Sat May  6 17:53:20 2017 [ 76 stmts 97 branches ]
Coverage.py warning: Couldn't read data from '/Users/alex/tstl/examples/c/coverage.out': CoverageException: Doesn't seem to be a coverage.py data file
STOPPING TEST DUE TO TIMEOUT, TERMINATED AT LENGTH 96
STOPPING TESTING DUE TO TIMEOUT
-1 PERCENT COVERED
60.0093560219 TOTAL RUNTIME
62 EXECUTED
6196 TOTAL TEST OPERATIONS
27.1253697872 TIME SPENT EXECUTING TEST OPERATIONS
32.2995955944 TIME SPENT EVALUATING GUARDS AND CHOOSING ACTIONS
0.00854253768921 TIME SPENT CHECKING PROPERTIES
27.1339123249 TOTAL TIME SPENT RUNNING SUT
0.1205701828 TIME SPENT RESTARTING
0.0 TIME SPENT REDUCING TEST CASES
0 FAILED
0 REPEATS OF FAILURES
0 ACTUAL DISTINCT FAILURES

97 BRANCHES COVERED
76 STATEMENTS COVERED
